;; generated by flanders.json-schema-test/generate-expected-schema-results
(ns flanders.json-schema.test-helpers-schema-security-finding)
(def
 expected-schema-explain
 '{:activity_id (enum 0 1 99 3 2),
   :category_uid Int,
   :class_uid Int,
   :cloud
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_cloud),
   :finding
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_finding),
   :metadata
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_metadata),
   :osint
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_osint)],
   :severity_id (enum 0 1 4 99 6 3 2 5),
   :state_id (enum 0 1 4 99 3 2),
   :time Int,
   :type_uid Int,
   (optional-key :activity_name) Str,
   (optional-key :analytic)
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_analytic),
   (optional-key :api)
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_api),
   (optional-key :attacks)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_attack)],
   (optional-key :category_name) Str,
   (optional-key :cis_csc)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_cis_csc)],
   (optional-key :class_name) Str,
   (optional-key :compliance)
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_compliance),
   (optional-key :confidence) Str,
   (optional-key :confidence_id) (enum 0 1 99 3 2),
   (optional-key :confidence_score) Int,
   (optional-key :count) Int,
   (optional-key :data_sources) [Str],
   (optional-key :duration) Int,
   (optional-key :end_time) Int,
   (optional-key :end_time_dt) Str,
   (optional-key :enrichments)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_enrichment)],
   (optional-key :evidence) Any,
   (optional-key :impact) Str,
   (optional-key :impact_id) (enum 0 1 4 99 3 2),
   (optional-key :impact_score) Int,
   (optional-key :kill_chain)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_kill_chain_phase)],
   (optional-key :malware)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_malware)],
   (optional-key :message) Str,
   (optional-key :nist) [Str],
   (optional-key :observables)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_observable)],
   (optional-key :process)
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_process),
   (optional-key :raw_data) Str,
   (optional-key :resources)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_resource_details)],
   (optional-key :risk_level) Str,
   (optional-key :risk_level_id) (enum 0 1 4 99 3 2),
   (optional-key :risk_score) Int,
   (optional-key :severity) Str,
   (optional-key :start_time) Int,
   (optional-key :start_time_dt) Str,
   (optional-key :state) Str,
   (optional-key :status) Str,
   (optional-key :status_code) Str,
   (optional-key :status_detail) Str,
   (optional-key :status_id) (enum 0 1 99 2),
   (optional-key :time_dt) Str,
   (optional-key :timezone_offset) Int,
   (optional-key :type_name) Str,
   (optional-key :unmapped)
   (recursive
    #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_object),
   (optional-key :vulnerabilities)
   [(recursive
     #'https_COLON__SLASH__SLASH_schema_DOT_ocsf_DOT_io_SLASH_schema_SLASH_classes_SLASH_security_finding_SLASH_$defs_SLASH_vulnerability)]})
