name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # 12:00AM on the first of every month
    - cron: "0 0 1 * *"

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 2.11.2
      - name: Cache project dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/project.clj', '**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-
      - name: Warm deps cache
        run: |
          for i in {1..10}; do lein deps :tree && break; done
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          clj-kondo: '2024.09.27'

      - name: Check clojure code
        run:
          ./bin/lint
  test:
    needs: setup
    strategy:
      matrix:
        jdk: ["21" "22"]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache project dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/project.clj', '**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure-
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 2.11.2
      - run: lein do clean, compile :all, test
  all-pr-checks:
    runs-on: ubuntu-22.04
    needs: [test, lint]
    steps:
      - run: echo "All tests pass!"
