name: Code check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          lein: latest
          cli: latest
          clj-kondo: latest

      - name: Check clojure code
        run:
          clj-kondo --lint ./src --lint ./test

      - name: Cache lein project dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/project.clj', '**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure

      - name: Run Clojure CLI tests
        run:
          clojure -X:test

      - name: Run leiningen tests
        run:
          lein test
